name: Docker

on:
  push:
    tags:
      - 'v*-fixed*'

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY_HOST }}/sympho-apps/pterodactyl
          flavor: |
            latest=auto
          tags: |
            type=ref,event=tag

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
